const express = require('express')
const router = express.Router()
const admincontroller=require("../Controller/AdminController")
const {upload}= require('../Middleware/Multer')
const { VerifyAdmin } = require('../Middleware/Auth')

router.post('/login',admincontroller.adminLogin)
router.get('/isAdminAuth',VerifyAdmin,admincontroller.isAdminAuth)
router.get('/getallmechanic',VerifyAdmin,admincontroller.getAllMechanicDetails)
router.get('/getallusers',VerifyAdmin,admincontroller.getAllUserDetails)
router.post('/addbrands',VerifyAdmin,upload.single('image'),admincontroller.addNewBrands)
router.get('/getallbrands',VerifyAdmin,admincontroller.getAllBrands)
router.post('/deletebrands/:id',VerifyAdmin,admincontroller.deleteBrand)
router.put('/blockuser/:id',VerifyAdmin,admincontroller.blockUser)
router.put('/unblockuser/:id',VerifyAdmin,admincontroller.unblockUser)
router.put('/updatebrand',VerifyAdmin,upload.single('image'),admincontroller.updateBrand)
router.post('/addservices',VerifyAdmin,upload.single('image'),admincontroller.addNewServices)
router.get('/getallservices',VerifyAdmin,admincontroller.getAllServices)
router.put('/updateservice' ,VerifyAdmin,upload.single('image'),admincontroller.updateService)
router.post('/deleteservice/:id',VerifyAdmin,admincontroller.deleteService)
router.get('/getallbrandNames',VerifyAdmin,admincontroller.getAllBrandNames)
 router.post('/addcarModels',VerifyAdmin,admincontroller.addcarModels)

 router.get('/getallcars',VerifyAdmin,admincontroller.getAllcarDetails)
 router.post('/deletecar/:id',VerifyAdmin,admincontroller.deleteCar)
router.put('/updatecars',VerifyAdmin,admincontroller.updateCar)
router.post('/addbanner',VerifyAdmin,upload.single('image'),admincontroller.addBanner)
router.get('/getallbanner',VerifyAdmin,admincontroller.getBanners)
router.put('/updatebanner',VerifyAdmin,upload.single('image'),admincontroller.updateBanner)
router.put('/blockbanner/:id',VerifyAdmin,admincontroller.blockBanner)
router.put('/unblockbanner/:id',VerifyAdmin,admincontroller.unblockBanner)
router.get('/getallServiceNames',VerifyAdmin,admincontroller.getServiceName)
router.post('/addserviceslist',VerifyAdmin,admincontroller.addServicesList)
router.get('/getallSiervicelsts',VerifyAdmin,admincontroller.getAllServiceList)
router.put('/updateservicelist',VerifyAdmin,admincontroller.updateServiceList)
router.post('/approvemechanic/:id',VerifyAdmin,admincontroller.mechanicApproval)
router.post('/rejectmechanic/:id',VerifyAdmin,admincontroller.mechanicReject)
router.post('/blockmechanic/:id',VerifyAdmin,admincontroller.mechanicBlock)
router.post('/addlocation',VerifyAdmin,admincontroller.addPlaces)
router.get('/getalllocations',VerifyAdmin,admincontroller.allLocations)
router.post('/deleteloc/:id',VerifyAdmin,admincontroller.deleteLocation)


module.exports = router;